### PR TITLE
Initial commit for MutableBulkheadPolicy

### PR DESCRIPTION
**Pull request by atifield**
- Most build scripts are from base template from PollyContrib
- `MutableBulkheadPolicy` code is modified from base `Bulkhead` code from Polly
- `SemaphoreSlimDynamic` is the basis for mutability and should be closely reviewed. It is just a wrapper over existing `SemaphoreSlim`
- Tests for `SemaphoreSlimDynamic` are modified from dotnet core unit tests.
- License has been updated copyright from Microsoft. Polly/AppvNext license is still included to comply to BSD3 license requirements. This is due to project developed under MSFT. All other copyright changes are to comply to MSFT OSS legal reviews.

### CODE REVIEW

**Comment by reisenberger** [comment]
Thanks @atifield ! I will read and comment soon as I get a suitable time slice, hopefully soon.

**Comment by reisenberger** [comment]
@atifield  Sorry that it has been a while before I can get to this (not forgotten it); thank you for your patience.

**Comment by reisenberger** [comment]
Thank you @atifield for putting the time into this feature. Also thank you for your patience before I got to review.

I like the overall approach: I had had a similar idea about avoiding blocking when no slots were available and capacity was to be decreased, by choosing not-to-release the necessary number of times, when user code later requests releases.

The unit test `RunSemaphoreSlimDynamicTest11_ConcurrentSetAvailableSlot()` is failing sporadically both when run within Visual Studio 2019, and when run from the build script, with:

```
Assert.Equal() Failure
Expected: 3
Actual:   1  // sometimes also with Actual: 2
   at Polly.Contrib.MutableBulkheadPolicy.Specs.SemaphoreSlimDynamicTests.RunSemaphoreSlimDynamicTest11_Internal(Int32 min, Int32 initial, Int32 max, Int32 initCount, Int32 finalCount, ValueTuple`2[] actions) in D:\zcode\GitHub\Polly-Contrib\Polly.Contrib.MutableBulkheadPolicy\src\Polly.Contrib.MutableBulkheadPolicy.Specs\SemaphoreSlimDynamicSpecs.cs:line 817
   at Polly.Contrib.MutableBulkheadPolicy.Specs.SemaphoreSlimDynamicTests.RunSemaphoreSlimDynamicTest11_ConcurrentSetAvailableSlot() in D:\zcode\GitHub\Polly-Contrib\Polly.Contrib.MutableBulkheadPolicy\src\Polly.Contrib.MutableBulkheadPolicy.Specs\SemaphoreSlimDynamicSpecs.cs:line 765
```

(I have not dug deep into why yet.)  

Thoughts?

**Comment by atifield** [comment]
@reisenberger Thanks for taking your time for reviewing. I will take a look at this flaky test and see what the issue is.

**Comment by atifield** [comment]
Fixed the flaky test. It was caused by SemaphoreFullException when the max is set lower than possible due to out of order action execution.

**Comment by reisenberger** [comment]
Thanks @atifield . Good, that was my assumption about the flaky test too - non-deterministic (rightly non-deterministic) order of actions queued up to compete concurrently, and ~3 + 2 > 4~ 2 + 2 > 3 in the case the two releases executed straight after reducing the bulkhead capacity. But wanted you to have the overview of it.

[The build](https://ci.appveyor.com/project/Polly-Contrib/polly-contrib-mutablebulkheadpolicy/builds/27949923) failed with:

    The type or namespace name 'SilentOutput' could not be found 

Something missing from the commit? Maybe just a `using` statement?

**Comment by atifield** [comment]
Sorry my bad. I should have tested building release as well.

**Review by reisenberger — APPROVED** [review]
Thank you @atifield for contributing this, and for inviting me to review.

I made a small PR #2 to describe capacity adjustment in more detail in the ReadMe - please feel free to merge this into your `Init` branch before merging to `master`, if you agree it is useful.

Otherwise :+1: for merge and release. 

You should have rights to merge PRs on this repo (part of the idea of `Polly-Contrib` is that contributors can own and maintain contributions), so please do go ahead and merge after considering #2 .

Thanks again!

**Comment by atifield** [comment]
Thank you for your review, @reisenberger. I have merged your doc PR and updated the version from #3 .

**Pull request merged**
